<?php

/**
 * Contest, ContestPatronage, ContestSection, import from file
 *   generated by app/Jobs/Backup/ContestAndRelated1stRestoreJob.php
 *
 */

namespace App\Jobs\Imports;

use App\Models\Contest;
use App\Models\ContestAward;
use App\Models\ContestJury;
use App\Models\ContestPatronage;
use App\Models\ContestSection;
use App\Models\Organization;
use App\Models\User;
use App\Models\UserContact;
use Carbon\Carbon;
use Illuminate\Bus\Queueable;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Foundation\Bus\Dispatchable;
use Illuminate\Queue\InteractsWithQueue;
use Illuminate\Queue\SerializesModels;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Facades\Storage;
use Symfony\Component\Yaml\Yaml;

class ContestAndRelated1stRestoreJob implements ShouldQueue
{
    use Dispatchable;
    use InteractsWithQueue;
    use Queueable;
    use SerializesModels;

    /**
     * Create a new job instance.
     *
     * @param string $yamlFilePath Percorso assoluto o relativo del file YAML di backup da ripristinare
     */
    public function __construct(
        public User $requesterUser,
        public string $relativeFilePath
    ) {
    }

    /**
     * Execute the job.
     */
    public function handle(): void
    {
        Log::info('Job: ' . class_basename($this) . ' / 1. started');
        Log::info('Job: ' . class_basename($this) . ' / 1. user:' . $this->requesterUser->name);
        Log::info('Job: ' . class_basename($this) . ' / 1. path:' . $this->relativeFilePath);
        $errors = [];
        $fullPath = Storage::disk('public')->path($this->relativeFilePath);
        $fullPath = str_ireplace('/private/', '/public/', $fullPath);
        Log::info('Job: ' . class_basename($this) . ' / 2. search: ' . $fullPath);

        // 1. Verifica esistenza file
        if (! Storage::disk('public')->path($this->relativeFilePath)) {
            $this->writeReportLog(["File non trovato: {$this->relativeFilePath}"]);
            return;
        }
        Log::info('Job: ' . class_basename($this) . ' / 2. file found');

        // 2. Parsing del file YAML/Testo
        try {
            $parsedData = Yaml::parseFile($fullPath);
        } catch (Throwable $e) {
            Log::info('Job: ' . class_basename($this) . ' / 3. parsed with errors');
            $this->writeReportLog(["Errore durante il parsing del file: " . $e->getMessage()]);
            return;
        }

        Log::info('Job: ' . class_basename($this) . ' / 3. parsed quiet');
        if (empty($parsedData['contests']) || !is_array($parsedData['contests'])) {
            Log::info('Job: ' . class_basename($this) . ' / 4. No contest found into file YAML.');
            return;
        }

        $importedCount = 0;

        // 2. Iterazione sui concorsi presenti nel file
        foreach ($parsedData['contests'] as $indexRow => $contestData) {
            $contestId = $contestData['id'] ?? null;
            if (!$contestId) {
                $errors[] = __("Row: :indexRow, no id found for Contest", ['indexRow' => $indexRow]);
                continue;
            }
            //
            try {
                DB::transaction(function () use ($contestData, &$importedCount) {
                    // A. Ripristino / Upsert dell'Organizzazione (se fornita)
                    if (!empty($contestData['organization'])) {
                        $orgData = $contestData['organization'];
                        Organization::updateOrCreate(
                            ['id' => $orgData['id']],
                            [
                                'name' => $orgData['name'] ?? '',
                                'email' => $orgData['email'] ?? null,
                                'country_id' => $orgData['country'] ?? null,
                            ]
                        );
                    }

                    // B. Ripristino / Upsert del Contest principale
                    $dates = $contestData['dates'] ?? [];

                    $contest = Contest::withTrashed()->updateOrCreate(
                        ['id' => $contestData['id']],
                        [
                            'name_en' => $contestData['name_en'] ?? '',
                            'is_circuit' => (bool)($contestData['is_circuit'] ?? false),
                            'circuit_id' => $contestData['circuit_id'] ?? null,
                            'country_id' => $contestData['country_id'] ?? null,
                            'vote_rule' => $contestData['vote_rule'] ?? 'num:1..10',
                            'organization_id' => $contestData['organization']['id'] ?? null,

                            // Mappatura date
                            'day_1_opening' => isset($dates['day_1_opening']) ? Carbon::parse($dates['day_1_opening']) : null,
                            'day_2_closing' => isset($dates['day_2_closing']) ? Carbon::parse($dates['day_2_closing']) : null,
                            'day_3_jury_opening' => isset($dates['day_3_jury_opening']) ? Carbon::parse($dates['day_3_jury_opening']) : null,
                            'day_4_jury_closing' => isset($dates['day_4_jury_closing']) ? Carbon::parse($dates['day_4_jury_closing']) : null,
                            'day_5_revelations' => isset($dates['day_5_revelations']) ? Carbon::parse($dates['day_5_revelations']) : null,
                            'day_6_awards' => isset($dates['day_6_awards']) ? Carbon::parse($dates['day_6_awards']) : null,
                            'day_7_catalogues' => isset($dates['day_7_catalogues']) ? Carbon::parse($dates['day_7_catalogues']) : null,
                            'day_8_closing' => isset($dates['day_8_closing']) ? Carbon::parse($dates['day_8_closing']) : null,
                        ]
                    );

                    // Ripristina nel caso il record fosse marcato come SoftDeleted
                    if ($contest->trashed()) {
                        $contest->restore();
                    }

                    // C. Ripristino dei Patronati (ContestPatronage)
                    if (!empty($contestData['patronages']) && is_array($contestData['patronages'])) {
                        foreach ($contestData['patronages'] as $patronageData) {
                            ContestPatronage::withTrashed()->updateOrCreate(
                                ['id' => $patronageData['id']],
                                [
                                    'contest_id' => $contest->id,
                                    'federation_id' => $patronageData['federation_id'],
                                    'patronage_code' => $patronageData['patronage_code'] ?? '',
                                ]
                            );
                        }
                    }

                    // D. Ripristino delle Sezioni (ContestSection) e della Giuria (ContestJury)
                    if (!empty($contestData['sections']) && is_array($contestData['sections'])) {
                        foreach ($contestData['sections'] as $sectionData) {
                            $rules = $sectionData['rules'] ?? [];

                            $section = ContestSection::withTrashed()->updateOrCreate(
                                ['id' => $sectionData['id']],
                                [
                                    'contest_id' => $contest->id,
                                    'code' => $sectionData['code'],
                                    'name_en' => $sectionData['name_en'] ?? '',
                                    'under_patronage' => (bool)($sectionData['under_patronage'] ?? false),
                                    'monochromatic_required' => (bool)($sectionData['monochromatic_required'] ?? false),
                                    'raw_required' => (bool)($sectionData['raw_required'] ?? false),
                                    'min_works' => $rules['min_works'] ?? 0,
                                    'max_works' => $rules['max_works'] ?? 4,
                                    'short_size_max' => $rules['short_size_max'] ?? 1080,
                                    'long_size_max' => $rules['long_size_max'] ?? 1920,
                                    'file_size_max' => $rules['file_size_max'] ?? 2048000,
                                ]
                            );

                            if ($section->trashed()) {
                                $section->restore();
                            }

                            // Ripristino Giuria per Sezione
                            if (!empty($sectionData['juries']) && is_array($sectionData['juries'])) {
                                foreach ($sectionData['juries'] as $juryData) {
                                    ContestJury::withTrashed()->updateOrCreate(
                                        ['id' => $juryData['id']],
                                        [
                                            'contest_id' => $contest->id,
                                            'section_id' => $section->id,
                                            'user_id' => $juryData['user_id'],
                                            'is_president' => (bool)($juryData['is_president'] ?? false),
                                            'qualify' => $juryData['qualify'] ?? '',
                                        ]
                                    );
                                }
                            }
                        }
                    }

                    // E. Ripristino dei Premi (ContestAward)
                    if (!empty($contestData['awards']) && is_array($contestData['awards'])) {
                        foreach ($contestData['awards'] as $awardData) {
                            ContestAward::withTrashed()->updateOrCreate(
                                ['id' => $awardData['id']],
                                [
                                    'contest_id' => $contest->id,
                                    'section_id' => $awardData['section_id'] ?? null,
                                    'section_code' => $awardData['section_code'] ?? null,
                                    'award_code' => $awardData['award_code'],
                                    'award_name' => $awardData['award_name'] ?? '',
                                    'is_award' => (bool)($awardData['is_award'] ?? true),
                                    'winner_user_id' => $awardData['winner_user_id'] ?? null,
                                    'winner_work_id' => $awardData['winner_work_id'] ?? null,
                                    'winner_name' => $awardData['winner_name'] ?? '',
                                ]
                            );
                        }
                    }

                    $importedCount++;
                }); // DB::transaction()
            } catch (\Throwable $e) {
                $errors[] = "Contest {$contestId} ({$contestData['name']}): Errore di salvataggio - " . $e->getMessage();
            }
        } // foreach()

        // 4. Se sono stati riscontrati errori, genera il file di log
        if (!empty($errors)) {
            $this->writeReportLog($errors);
        } else {
          // use the same to say No errors
            $allQuite = [];
            $allQuite[] = "All works fine. Thanks";
            $this->writeReportLog($allQuite);
        }
    }

    /**
     * Scrive il report degli errori nella cartella storage/app/public/imports/
     */
    protected function writeReportLog(array $errors): void
    {
        $directory = pathinfo(path: $this->relativeFilePath, flags: PATHINFO_DIRNAME);
        $fileName = pathinfo(path: $this->relativeFilePath, flags: PATHINFO_FILENAME);
        $fileName = ($directory !== '.' ? $directory . '/' : '') . "{$fileName}_report.txt";

        $content = "==================================================\n";
        $content .= __("IMPORT REPORT") . "\n";
        $content .= __("Requester") . ": {$this->requesterUser->name} (ID: {$this->requesterUser->id})\n";
        $content .= __("Import Date") . ": " . now()->toDateTimeString() . "\n";
        $content .= "==================================================\n\n";
        $content .= implode("\n", $errors) . "\n";

        // Salva specificamente nel disk public
        Storage::disk('public')->put($fileName, $content);
    }
}
