<?php

/**
 * User, userContact, UserContactMore import from file
 *   generated by app/Jobs/Backups/UserAndRelatedBackupJob.php
 *
 */

namespace App\Jobs\Imports;

use App\Models\User;
use App\Models\UserContact;
use App\Models\UserContactMore;
use Illuminate\Bus\Queueable;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Foundation\Bus\Dispatchable;
use Illuminate\Queue\InteractsWithQueue;
use Illuminate\Queue\SerializesModels;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Facades\Storage;
use Symfony\Component\Yaml\Yaml;
use Throwable;

class ImportUserAndRelatedJob implements ShouldQueue
{
    use Dispatchable;
    use InteractsWithQueue;
    use Queueable;
    use SerializesModels;

    /**
     * Create a new job instance.
     *
     * @param User $requesterUser Utente che ha avviato l'importazione
     * @param string $relativeFilePath Percorso del file relativo allo storage (es. "import/backup_file.yaml")
     */
    public function __construct(
        public User $requesterUser,
        public string $relativeFilePath
    ) {
    }

    /**
     * Execute the job.
     */
    public function handle(): void
    {
        Log::info('Requested job: ' . class_basename($this) . ' / 1. started');
        Log::info('Requested job: ' . class_basename($this) . ' / 1. user:' . $this->requesterUser->name);
        Log::info('Requested job: ' . class_basename($this) . ' / 1. path:' . $this->relativeFilePath);
        $errors = [];
        $fullPath = Storage::disk('public')->path($this->relativeFilePath);
        $fullPath = str_ireplace('/private/', '/public/', $fullPath);
        Log::info('Requested job: ' . class_basename($this) . ' / 2. search: ' . $fullPath);

        // 1. Verifica esistenza file
        if (! Storage::disk('public')->path($this->relativeFilePath)) {
            $this->writeReportLog(["File non trovato: {$this->relativeFilePath}"]);
            return;
        }
        Log::info('Requested job: ' . class_basename($this) . ' / 2. file found');

        // 2. Parsing del file YAML/Testo
        try {
            $parsedData = Yaml::parseFile($fullPath);
        } catch (Throwable $e) {
            Log::info('Requested job: ' . class_basename($this) . ' / 3. parsed with errors');
            $this->writeReportLog(["Errore durante il parsing del file: " . $e->getMessage()]);
            return;
        }

        Log::info('Requested job: ' . class_basename($this) . ' / 3. parsed quiet');
        $data = $parsedData['data'] ?? [];
        $users = $data['users'] ?? [];
        $contacts = collect($data['user_contacts'] ?? [])->keyBy('id');
        $contactMores = collect($data['user_contact_mores'] ?? [])->groupBy('user_id');

        // 3. Lavorazione e aggiornamento/inserimento per ciascun utente
        foreach ($users as $index => $userData) {
            $userId = $userData['id'] ?? null;

            if (!$userId) {
                $errors[] = "Riga {$index}: Record User privo di ID univoco.";
                continue;
            }

            try {
                DB::transaction(function () use ($userData, $userId, $contacts, $contactMores) {
                    // Upsert Model User (gestisce anche record soft-deleted se abilitati)
                    User::withTrashed()->updateOrCreate(
                        ['id' => $userId],
                        $userData
                    );

                    // Upsert Model UserContact
                    if ($contactData = $contacts->get($userId)) {
                        UserContact::withTrashed()->updateOrCreate(
                            ['id' => $userId],
                            $contactData
                        );
                    }

                    // Upsert Model UserContactMore
                    if ($userMores = $contactMores->get($userId)) {
                        foreach ($userMores as $moreData) {
                            UserContactMore::withTrashed()->updateOrCreate(
                                ['id' => $moreData['id']],
                                $moreData
                            );
                        }
                    }
                });
            } catch (Throwable $e) {
                $errors[] = "User ID {$userId} ({$userData['email']}): Errore di salvataggio - " . $e->getMessage();
            }
        }

        // 4. Se sono stati riscontrati errori, genera il file di log
        if (!empty($errors)) {
            $this->writeReportLog($errors);
        } else {
          // use the same to say No errors
            $allQuite = [];
            $allQuite[] = "All works fine. Thanks";
            $this->writeReportLog($allQuite);
        }
    }

    /**
     * Scrive il report degli errori nella cartella storage/app/public/imports/
     */
    protected function writeReportLog(array $errors): void
    {
        $directory = pathinfo(path: $this->relativeFilePath, flags: PATHINFO_DIRNAME);
        $fileName = pathinfo(path: $this->relativeFilePath, flags: PATHINFO_FILENAME);
        $fileName = ($directory !== '.' ? $directory . '/' : '') . "{$fileName}_report.txt";

        $content = "==================================================\n";
        $content .= __("IMPORT REPORT") . "\n";
        $content .= __("Requester") . ": {$this->requesterUser->name} (ID: {$this->requesterUser->id})\n";
        $content .= __("Import Date") . ": " . now()->toDateTimeString() . "\n";
        $content .= "==================================================\n\n";
        $content .= implode("\n", $errors) . "\n";

        // Salva specificamente nel disk public
        Storage::disk('public')->put($fileName, $content);
    }
}
