<?php

/**
 * UserWork, userWorkMore, and User, UserContact import from yaml file
 *   generated by app/Jobs/backup/UserWorkAndRelatedBackup.Jobs.php
 * Another job can import similar yaml file but human edited and
 *   with different rules() [i.e. use of 'new' token].
 */

namespace App\Jobs\Imports;

use App\Models\User;
use App\Models\UserContact;
use App\Models\UserWork;
use App\Models\UserWorkMore;
use Illuminate\Bus\Queueable;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Foundation\Bus\Dispatchable;
use Illuminate\Queue\InteractsWithQueue;
use Illuminate\Queue\SerializesModels;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Facades\Storage;
use Symfony\Component\Yaml\Yaml;
use Throwable;

class UserWorkAndRelatedRestoreJob implements ShouldQueue
{
    use Dispatchable;
    use InteractsWithQueue;
    use Queueable;
    use SerializesModels;

    /**
     * Create a new job instance.
     *
     * @param User $requesterUser utente abilitato dalle Policy ad eseguire il job
     * @param string $yamlPath Percorso del file YAML
     */
    public function __construct(
        public User $requesterUser, // external policy checked
        public string $yamlPath
    ) {
        $this->requesterUser = $requesterUser;
        $this->yamlPath      = $yamlPath;
    }

    /**
     * Execute the job.
     */
    public function handle(): void
    {
        Log::info('Job: ' . class_basename($this) . ' / 1. started');
        Log::info('Job: ' . class_basename($this) . ' / 1. user:' . $this->requesterUser->name);
        Log::info('Job: ' . class_basename($this) . ' / 1. path:' . $this->yamlPath);
        $errors = [];
        $fullPath = Storage::disk('public')->path($this->yamlPath);
        $fullPath = str_ireplace('/private/', '/public/', $fullPath); // check if removable, now?
        Log::info('Job: ' . class_basename($this) . ' / 2. search: ' . $fullPath);

        // 1. Found / not found that's the issue
        if (! Storage::disk('public')->path($this->yamlPath)) {
            Log::error('Job: ' . class_basename($this) . ' / 2. file not found');
            $this->writeReportLog(["File not found: {$this->yamlPath}"]);
            return;
        }
        Log::info('Job: ' . class_basename($this) . ' / 2. file found');

        if (!file_exists($this->yamlPath)) {
            Log::error('Job: ' . class_basename($this) . ' / 2. file not found', [
                'path' => $this->yamlPath
            ]);
            throw new \InvalidArgumentException("File YAML not found: {$this->yamlPath}");
        }

        // 2. Parsing YAML input
        try {
            $parsedYaml = Yaml::parseFile($fullPath); // was: ($this->yamlPath);
            $data = $parsedYaml['data'] ?? [];
        } catch (Throwable $e) {
            Log::error('Job: ' . class_basename($this) . ' / 3. file not parsed', [
                'path' => $this->yamlPath,
                'error_message' => $e->getMessage(),
                'file' => $e->getFile(),
                'line' => $e->getLine()
            ]);
            throw $e;
        }

        // All ok or nothing done, that's transaction rollback
        DB::transaction(function () use ($data) {
            // 1. Restore / Update User
            if (!empty($data['users'])) {
                foreach ($data['users'] as $index => $userData) {
                    try {
                        User::withTrashed()->updateOrCreate(
                            ['id' => $userData['id']],
                            $userData
                        );
                    } catch (Throwable $e) {
                        Log::error("UserWorkAndRelatedRestoreJob - Errore durante l'importazione di User", [
                            'array_index' => $index,
                            'record_id' => $userData['id'] ?? null,
                            'payload' => $userData,
                            'error_message' => $e->getMessage(),
                            'file' => $e->getFile(),
                            'line' => $e->getLine()
                        ]);
                        throw $e; // Interrompe e fa il rollback della transazione
                    }
                }
            }

            // 2. Restore / Update UserContact
            if (!empty($data['user_contacts'])) {
                foreach ($data['user_contacts'] as $index => $contactData) {
                    try {
                        UserContact::withTrashed()->updateOrCreate(
                            ['id' => $contactData['id']],
                            $contactData
                        );
                    } catch (Throwable $e) {
                        Log::error("UserWorkAndRelatedRestoreJob - Errore durante l'importazione di UserContact", [
                            'array_index' => $index,
                            'record_id' => $contactData['id'] ?? null,
                            'payload' => $contactData,
                            'error_message' => $e->getMessage(),
                            'file' => $e->getFile(),
                            'line' => $e->getLine()
                        ]);
                        throw $e;
                    }
                }
            }

            // 3. Restore / Update UserWork
            if (!empty($data['user_works'])) {
                foreach ($data['user_works'] as $index => $workData) {
                    try {
                        UserWork::withTrashed()->updateOrCreate(
                            ['id' => $workData['id']],
                            $workData
                        );
                    } catch (Throwable $e) {
                        Log::error("UserWorkAndRelatedRestoreJob - Errore durante l'importazione di UserWork", [
                            'array_index' => $index,
                            'record_id' => $workData['id'] ?? null,
                            'payload' => $workData,
                            'error_message' => $e->getMessage(),
                            'file' => $e->getFile(),
                            'line' => $e->getLine()
                        ]);
                        throw $e;
                    }
                }
            }

            // 4. Restore / Update UserWorkMore
            if (!empty($data['user_work_mores'])) {
                foreach ($data['user_work_mores'] as $index => $workMoreData) {
                    try {
                        UserWorkMore::withTrashed()->updateOrCreate(
                            ['id' => $workMoreData['id']],
                            $workMoreData
                        );
                    } catch (Throwable $e) {
                        Log::error("UserWorkAndRelatedRestoreJob - Errore durante l'importazione di UserWorkMore", [
                            'array_index' => $index,
                            'record_id' => $workMoreData['id'] ?? null,
                            'payload' => $workMoreData,
                            'error_message' => $e->getMessage(),
                            'file' => $e->getFile(),
                            'line' => $e->getLine()
                        ]);
                        throw $e;
                    }
                }
            }
        });
    }

    /**
     * Handle a job failure.
     */
    public function failed(Throwable $exception): void
    {
        Log::critical("UserWorkAndRelatedRestoreJob - Job fallito definitivamente", [
            'path' => $this->yamlPath,
            'error_message' => $exception->getMessage(),
            'file' => $exception->getFile(),
            'line' => $exception->getLine()
        ]);
    }
}
